static const char* gaussian_blur_cl_source =
"float4 fir_get_mean_component_1D(const global float4 *buf,                    \n"
"                                    int offset,                               \n"
"                                    const int delta_offset,                   \n"
"                                    constant float *cmatrix,                  \n"
"                                    const int matrix_length)                  \n"
"{                                                                             \n"
"    float4 acc = 0.0f;                                                        \n"
"    int i;                                                                    \n"
"                                                                              \n"
"    for(i=0; i<matrix_length; i++)                                            \n"
"      {                                                                       \n"
"        acc    += buf[offset] * cmatrix[i];                                   \n"
"        offset += delta_offset;                                               \n"
"      }                                                                       \n"
"    return acc;                                                               \n"
"}                                                                             \n"
"                                                                              \n"
"__kernel void fir_ver_blur(const global float4 *src_buf,                      \n"
"                              const int src_width,                            \n"
"                              global float4 *dst_buf,                         \n"
"                              constant float *cmatrix,                        \n"
"                              const int matrix_length,                        \n"
"                              const int yoff)                                 \n"
"{                                                                             \n"
"    int gidx = get_global_id(0);                                              \n"
"    int gidy = get_global_id(1);                                              \n"
"    int gid  = gidx + gidy * get_global_size(0);                              \n"
"                                                                              \n"
"    int radius = matrix_length / 2;                                           \n"
"    int src_offset = gidx + (gidy - radius + yoff) * src_width;               \n"
"                                                                              \n"
"    dst_buf[gid] = fir_get_mean_component_1D(                                 \n"
"        src_buf, src_offset, src_width, cmatrix, matrix_length);              \n"
"}                                                                             \n"
"                                                                              \n"
"__kernel void fir_hor_blur(const global float4 *src_buf,                      \n"
"                              const int src_width,                            \n"
"                              global float4 *dst_buf,                         \n"
"                              constant float *cmatrix,                        \n"
"                              const int matrix_length,                        \n"
"                              const int yoff)                                 \n"
"{                                                                             \n"
"    int gidx = get_global_id(0);                                              \n"
"    int gidy = get_global_id(1);                                              \n"
"    int gid  = gidx + gidy * get_global_size(0);                              \n"
"                                                                              \n"
"    int radius = matrix_length / 2;                                           \n"
"    int src_offset = gidy * src_width + (gidx - radius + yoff);               \n"
"                                                                              \n"
"    dst_buf[gid] = fir_get_mean_component_1D(                                 \n"
"        src_buf, src_offset, 1, cmatrix, matrix_length);                      \n"
"}                                                                             \n"
;
