static const char* kernel_color_source =
"/* This is almost a copy-paste from babl/base conversion functions in RGBA space */      \n"
"                                                                                         \n"
"/* Alpha threshold used in the reference implementation for                              \n"
" * un-pre-multiplication of color data:                                                  \n"
" *                                                                                       \n"
" * 0.01 / (2^16 - 1)                                                                     \n"
" */                                                                                      \n"
"#define BABL_ALPHA_THRESHOLD 0.000000152590219                                           \n"
"                                                                                         \n"
"float linear_to_gamma_2_2 (float value)                                                  \n"
"{                                                                                        \n"
"  if (value > 0.0030402477f)                                                             \n"
"    return 1.055f * native_powr (value, (1.0f/2.4f)) - 0.055f;                           \n"
"  return 12.92f * value;                                                                 \n"
"}                                                                                        \n"
"                                                                                         \n"
"float gamma_2_2_to_linear (float value)                                                  \n"
"{                                                                                        \n"
"  if (value > 0.03928f)                                                                  \n"
"    return native_powr ((value + 0.055f) / 1.055f, 2.4f);                                \n"
"  return value / 12.92f;                                                                 \n"
"}                                                                                        \n"

/* -- RGBA float/u8 -- */

/* RGBA u8 -> RGBA float */
"__kernel void rgbau8_to_rgbaf (__global const uchar4 * in,                               \n"
"                               __global       float4 * out)                              \n"
"{                                                                                        \n"
"  int gid = get_global_id(0);                                                            \n"
"  float4 in_v  = convert_float4(in[gid]) / 255.0f;                                       \n"
"  float4 out_v = in_v;                                                                   \n"
"  out[gid] = out_v;                                                                      \n"
"}                                                                                        \n"

/* RGBA float -> RGBA u8 */
"__kernel void rgbaf_to_rgbau8 (__global const float4 * in,                               \n"
"                               __global       uchar4 * out)                              \n"
"{                                                                                        \n"
"  int gid = get_global_id(0);                                                            \n"
"  float4 in_v  = in[gid];                                                                \n"
"  float4 out_v = in_v;                                                                   \n"
"  out[gid] = convert_uchar4_sat_rte(255.0f * out_v);                                     \n"
"}                                                                                        \n"

/* -- RaGaBaA float -- */

/* RGBA float -> RaGaBaA float */
"__kernel void rgbaf_to_ragabaf (__global const float4 * in,                              \n"
"                                __global       float4 * out)                             \n"
"{                                                                                        \n"
"  int gid = get_global_id(0);                                                            \n"
"  float4 in_v = in[gid];                                                                 \n"
"  float4 out_v;                                                                          \n"
"  out_v   = in_v * in_v.w;                                                               \n"
"  out_v.w = in_v.w;                                                                      \n"
"  out[gid] = out_v;                                                                      \n"
"}                                                                                        \n"
"                                                                                         \n"

/* RaGaBaA float -> RGBA float */
"__kernel void ragabaf_to_rgbaf (__global const float4 * in,                              \n"
"                                __global       float4 * out)                             \n"
"{                                                                                        \n"
"  int gid = get_global_id(0);                                                            \n"
"  float4 in_v  = in[gid];                                                                \n"
"  float4 out_v;                                                                          \n"
"  out_v = (in_v.w > BABL_ALPHA_THRESHOLD)? in_v / in_v.w : (float4)(0.0f);               \n"
"  out_v.w = in_v.w;                                                                      \n"
"  out[gid] = out_v;                                                                      \n"
"}                                                                                        \n"

/* RGBA u8 -> RaGaBaA float */
"__kernel void rgbau8_to_ragabaf (__global const uchar4 * in,                             \n"
"                                 __global       float4 * out)                            \n"
"{                                                                                        \n"
"  int gid = get_global_id(0);                                                            \n"
"  float4 in_v  = convert_float4(in[gid]) / 255.0f;                                       \n"
"  float4 out_v;                                                                          \n"
"  out_v   = in_v * in_v.w;                                                               \n"
"  out_v.w = in_v.w;                                                                      \n"
"  out[gid] = out_v;                                                                      \n"
"}                                                                                        \n"
"                                                                                         \n"

/* RaGaBaA float -> RGBA u8 */
"__kernel void ragabaf_to_rgbau8 (__global const float4 * in,                             \n"
"                                 __global       uchar4 * out)                            \n"
"{                                                                                        \n"
"  int gid = get_global_id(0);                                                            \n"
"  float4 in_v  = in[gid];                                                                \n"
"  float4 out_v;                                                                          \n"
"  out_v = (in_v.w > BABL_ALPHA_THRESHOLD)? in_v / in_v.w : (float4)(0.0f);               \n"
"  out_v.w = in_v.w;                                                                      \n"
"  out[gid] = convert_uchar4_sat_rte(out_v);                                              \n"
"}                                                                                        \n"

/* -- R'G'B'A float -- */

/* rgba float -> r'g'b'a float */
"__kernel void rgbaf_to_rgba_gamma_f (__global const float4 * in,                         \n"
"                                     __global       float4 * out)                        \n"
"{                                                                                        \n"
"  int gid = get_global_id(0);                                                            \n"
"  float4 in_v  = in[gid];                                                                \n"
"  float4 out_v;                                                                          \n"
"  out_v = (float4)(linear_to_gamma_2_2(in_v.x),                                          \n"
"                   linear_to_gamma_2_2(in_v.y),                                          \n"
"                   linear_to_gamma_2_2(in_v.z),                                          \n"
"                   in_v.w);                                                              \n"
"  out[gid] = out_v;                                                                      \n"
"}                                                                                        \n"

/* r'g'b'a float -> rgba float */
"__kernel void rgba_gamma_f_to_rgbaf (__global const float4 * in,                         \n"
"                                     __global       float4 * out)                        \n"
"{                                                                                        \n"
"  int gid = get_global_id(0);                                                            \n"
"  float4 in_v  = in[gid];                                                                \n"
"  float4 out_v;                                                                          \n"
"  out_v = (float4)(gamma_2_2_to_linear(in_v.x),                                          \n"
"                   gamma_2_2_to_linear(in_v.y),                                          \n"
"                   gamma_2_2_to_linear(in_v.z),                                          \n"
"                   in_v.w);                                                              \n"
"  out[gid] = out_v;                                                                      \n"
"}                                                                                        \n"

/* rgba u8 -> r'g'b'a float */
"__kernel void rgbau8_to_rgba_gamma_f (__global const uchar4 * in,                        \n"
"                                      __global       float4 * out)                       \n"
"{                                                                                        \n"
"  int gid = get_global_id(0);                                                            \n"
"  float4 in_v  = convert_float4(in[gid]) / 255.0f;                                       \n"
"  float4 out_v;                                                                          \n"
"  out_v = (float4)(linear_to_gamma_2_2(in_v.x),                                          \n"
"                   linear_to_gamma_2_2(in_v.y),                                          \n"
"                   linear_to_gamma_2_2(in_v.z),                                          \n"
"                   in_v.w);                                                              \n"
"  out[gid] = out_v;                                                                      \n"
"}                                                                                        \n"

/* r'g'b'a float -> rgba u8 */
"__kernel void rgba_gamma_f_to_rgbau8 (__global const float4 * in,                        \n"
"                                      __global       uchar4 * out)                       \n"
"{                                                                                        \n"
"  int gid = get_global_id(0);                                                            \n"
"  float4 in_v  = in[gid];                                                                \n"
"  float4 out_v;                                                                          \n"
"  out_v = (float4)(gamma_2_2_to_linear(in_v.x),                                          \n"
"                   gamma_2_2_to_linear(in_v.y),                                          \n"
"                   gamma_2_2_to_linear(in_v.z),                                          \n"
"                   in_v.w);                                                              \n"
"  out[gid] = convert_uchar4_sat_rte(255.0f * out_v);                                     \n"
"}                                                                                        \n"

/* -- Y'CbCrA float -- */

/* RGBA float -> Y'CbCrA float */
"__kernel void rgbaf_to_ycbcraf (__global const float4 * in,                              \n"
"                                __global       float4 * out)                             \n"
"{                                                                                        \n"
"  int gid = get_global_id(0);                                                            \n"
"  float4 in_v  = in[gid];                                                                \n"
"  float4 out_v;                                                                          \n"
"                                                                                         \n"
"  float4 rgb = (float4)(linear_to_gamma_2_2(in_v.x),                                     \n"
"                        linear_to_gamma_2_2(in_v.y),                                     \n"
"                        linear_to_gamma_2_2(in_v.z),                                     \n"
"                        0.0f);                                                           \n"
"                                                                                         \n"
"  out_v = (float4)( 0.299f    * rgb.x + 0.587f    * rgb.y + 0.114f    * rgb.z,           \n"
"                   -0.168736f * rgb.x - 0.331264f * rgb.y + 0.5f      * rgb.z,           \n"
"                    0.5f      * rgb.x - 0.418688f * rgb.y - 0.081312f * rgb.z,           \n"
"                   in_v.w);                                                              \n"
"  out[gid] = out_v;                                                                      \n"
"}                                                                                        \n"

/* Y'CbCrA float -> RGBA float */
"__kernel void ycbcraf_to_rgbaf (__global const float4 * in,                              \n"
"                                __global       float4 * out)                             \n"
"{                                                                                        \n"
"  int gid = get_global_id(0);                                                            \n"
"  float4 in_v  = in[gid];                                                                \n"
"  float4 out_v;                                                                          \n"
"                                                                                         \n"
"  float4 rgb = (float4)(1.0f * in_v.x + 0.0f      * in_v.y + 1.40200f    * in_v.z,       \n"
"                        1.0f * in_v.x - 0.344136f * in_v.y - 0.71414136f * in_v.z,       \n"
"                        1.0f * in_v.x + 1.772f    * in_v.y + 0.0f        * in_v.z,       \n"
"                        0.0f);                                                           \n"
"                                                                                         \n"
"  out_v = (float4)(linear_to_gamma_2_2(rgb.x),                                           \n"
"                   linear_to_gamma_2_2(rgb.y),                                           \n"
"                   linear_to_gamma_2_2(rgb.z),                                           \n"
"                   in_v.w);                                                              \n"
"  out[gid] = out_v;                                                                      \n"
"}                                                                                        \n"

/* RGBA u8 -> Y'CbCrA float */
"__kernel void rgbau8_to_ycbcraf (__global const uchar4 * in,                             \n"
"                                 __global       float4 * out)                            \n"
"{                                                                                        \n"
"  int gid = get_global_id(0);                                                            \n"
"  float4 in_v  = convert_float4(in[gid]) / 255.0f;                                       \n"
"  float4 out_v;                                                                          \n"
"                                                                                         \n"
"  float4 rgb = (float4)(linear_to_gamma_2_2(in_v.x),                                     \n"
"                        linear_to_gamma_2_2(in_v.y),                                     \n"
"                        linear_to_gamma_2_2(in_v.z),                                     \n"
"                        0.0f);                                                           \n"
"                                                                                         \n"
"  out_v = (float4)( 0.299f    * rgb.x + 0.587f    * rgb.y + 0.114f    * rgb.z,           \n"
"                   -0.168736f * rgb.x - 0.331264f * rgb.y + 0.5f      * rgb.z,           \n"
"                    0.5f      * rgb.x - 0.418688f * rgb.y - 0.081312f * rgb.z,           \n"
"                   in_v.w);                                                              \n"
"  out[gid] = out_v;                                                                      \n"
"}                                                                                        \n"

/* Y'CbCrA float -> RGBA u8 */
"__kernel void ycbcraf_to_rgbau8 (__global const float4 * in,                             \n"
"                                 __global       uchar4 * out)                            \n"
"{                                                                                        \n"
"  int gid = get_global_id(0);                                                            \n"
"  float4 in_v  = in[gid];                                                                \n"
"  float4 out_v;                                                                          \n"
"                                                                                         \n"
"  float4 rgb = (float4)(1.0f * in_v.x + 0.0f      * in_v.y + 1.40200f    * in_v.z,       \n"
"                        1.0f * in_v.x - 0.344136f * in_v.y - 0.71414136f * in_v.z,       \n"
"                        1.0f * in_v.x + 1.772f    * in_v.y + 0.0f        * in_v.z,       \n"
"                        0.0f);                                                           \n"
"                                                                                         \n"
"  out_v = (float4)(linear_to_gamma_2_2(rgb.x),                                           \n"
"                   linear_to_gamma_2_2(rgb.y),                                           \n"
"                   linear_to_gamma_2_2(rgb.z),                                           \n"
"                   in_v.w);                                                              \n"
"  out[gid] = convert_uchar4_sat_rte(255.0f * out_v);                                     \n"
"}                                                                                        \n";
