/* rgegl - a ruby binding for GEGL
 *
 * rgegl is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 3 of the License, or (at your option) any later version.
 *
 * GEGL is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with rgegl; if not, write to the
 * Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
 * Boston, MA 02110-1301, USA.
 *
 * 2007 © Øyvind Kolås.
 */

/* -*- c-file-style: "ruby"; indent-tabs-mode: nil -*- */
/************************************************

  rbgeglversion.h -

  This file was generated by mkmf-gnome2.rb.

************************************************/

#ifndef __RBGEGL_VERSION_H__
#define __RBGEGL_VERSION_H__

#define GEGL_MAJOR_VERSION (0)
#define GEGL_MINOR_VERSION (0)
#define GEGL_MICRO_VERSION (7)

#define GEGL_CHECK_VERSION(major,minor,micro)    \
    (GEGL_MAJOR_VERSION > (major) || \
     (GEGL_MAJOR_VERSION == (major) && GEGL_MINOR_VERSION > (minor)) || \
     (GEGL_MAJOR_VERSION == (major) && GEGL_MINOR_VERSION == (minor) && \
      GEGL_MICRO_VERSION >= (micro)))


#endif /* __RBGEGL_VERSION_H__ */
