#ifndef __GEGL_H__
#define __GEGL_H__
#include <gegl-add-op.h>
#include <gegl-cache.h>
#include <gegl-color-convert-op.h>
#include <gegl-color-convert-to-gray-op.h>
#include <gegl-color-convert-to-rgb-op.h>
#include <gegl-color-model-gray.h>
#include <gegl-color-model-gray-u8.h>
#include <gegl-color-model-gray-float.h>
#include <gegl-color-model-gray-u16.h>
#include <gegl-color-model-gray-u16_4.h>
#include <gegl-color-model-rgb.h>
#include <gegl-color-model-rgb-u8.h>
#include <gegl-color-model-rgb-float.h>
#include <gegl-color-model-rgb-u16.h>
#include <gegl-color-model-rgb-u16_4.h>
#include <gegl-color-model.h>
#include <gegl-color.h>
#include <gegl-composite-op.h>
#include <gegl-composite-premult-op.h>
#include <gegl-copy-op.h>
#include <gegl-dark-op.h>
#include <gegl-data-buffer.h>
#include <gegl-diff-op.h>
#include <gegl-dual-src-op.h>
#include <gegl-fill-op.h>
#include <gegl-image.h>
#include <gegl-image-buffer.h>
#include <gegl-image-manager.h>
#include <gegl-light-op.h>
#include <gegl-max-op.h>
#include <gegl-min-op.h>
#include <gegl-mult-op.h>
#include <gegl-n-src-op.h>
#include <gegl-node.h>
#include <gegl-object.h>
#include <gegl-op.h>
#include <gegl-point-op.h>
#include <gegl-premult-op.h>
#include <gegl-print-op.h>
#include <gegl-screen-op.h>
#include <gegl-single-src-op.h>
#include <gegl-statistics-op.h>
#include <gegl-subtract-op.h>
#include <gegl-test-op.h>
#include <gegl-tile.h>
#include <gegl-tile-image-manager.h>
#include <gegl-tile-iterator.h>
#include <gegl-unpremult-op.h>
#include <gegl-types.h>
#include <gegl-utils.h>
#endif
