#ifndef __GEGL_H__
#define __GEGL_H__
#include <gegl-add.h>
#include <gegl-bfs-visitor.h>
#include <gegl-binary.h>
#include <gegl-blend.h>
#include <gegl-channels.h>
#include <gegl-color.h>
#include <gegl-color-data.h>
#include <gegl-color-model.h>
#include <gegl-color-space.h>
#include <gegl-color-space-rgb.h>
#include <gegl-color-space-gray.h>
#include <gegl-comp.h>
#include <gegl-component-storage.h>
#include <gegl-component-color-model.h>
#include <gegl-data.h>
#include <gegl-buffer.h>
#include <gegl-dfs-visitor.h>
#include <gegl-dump-visitor.h>
#include <gegl-eval-bfs-visitor.h>
#include <gegl-eval-dfs-visitor.h>
#include <gegl-eval-mgr.h>
#include <gegl-eval-visitor.h>
#include <gegl-fade.h>
#include <gegl-fill.h>
#include <gegl-filter.h>
#include <gegl-graph.h>
#include <gegl-graph-setup-visitor.h>
#include <gegl-i-add.h>
#include <gegl-image-op.h>
#include <gegl-image.h>
#include <gegl-image-data.h>
#include <gegl-image-iterator.h>
#include <gegl-image-op-interface.h>
#include <gegl-init.h>
#include <gegl-mult.h>
#include <gegl-multi-image-op.h>
#include <gegl-multiply.h>
#include <gegl-no-input.h>
#include <gegl-node.h>
#include <gegl-object.h>
#include <gegl-op.h>
#include <gegl-over.h>
#include <gegl-param-specs.h>
#include <gegl-pipe.h>
#include <gegl-point-op.h>
#include <gegl-print.h>
#include <gegl-scalar-data.h>
#include <gegl-scanline-processor.h>
#include <gegl-storage.h>
#include <gegl-tile.h>
#include <gegl-types.h>
#include <gegl-unary.h>
#include <gegl-value-types.h>
#include <gegl-visitor.h>
#endif
