#ifndef __GEGL_H__
#define __GEGL_H__
#include <gegl-add.h>
#include <gegl-buffer.h>
#include <gegl-color-model-gray-float.h>
#include <gegl-color-model-gray-u16.h>
#include <gegl-color-model-gray-u8.h>
#include <gegl-color-model-gray.h>
#include <gegl-color-model-rgb-float.h>
#include <gegl-color-model-rgb-u16.h>
#include <gegl-color-model-rgb-u8.h>
#include <gegl-color-model-rgb.h>
#include <gegl-color-model.h>
#include <gegl-color.h>
#include <gegl-comp-premult.h>
#include <gegl-comp.h>
#include <gegl-const-mult.h>
#include <gegl-copy.h>
#include <gegl-dark.h>
#include <gegl-diff.h>
#include <gegl-fill.h>
#include <gegl-filter.h>
#include <gegl-image.h>
#include <gegl-light.h>
#include <gegl-max.h>
#include <gegl-mem-buffer.h>
#include <gegl-min.h>
#include <gegl-mult.h>
#include <gegl-node.h>
#include <gegl-object.h>
#include <gegl-op.h>
#include <gegl-param-specs.h>
#include <gegl-point-op.h>
#include <gegl-premult.h>
#include <gegl-print.h>
#include <gegl-sampled-image.h>
#include <gegl-scanline-processor.h>
#include <gegl-screen.h>
#include <gegl-stat-op.h>
#include <gegl-subtract.h>
#include <gegl-tile-iterator.h>
#include <gegl-tile-mgr.h>
#include <gegl-tile.h>
#include <gegl-unpremult.h>
#include <gegl-value-types.h>
#include <gegl-visitor.h>
#endif
