#!/bin/sh

echo "
/* WARNING: Autogenerated file based on object definitions
 found in headers in directorty.
*/
#include <glib-object.h>

#include <stdio.h>
"

type_funs=`cat *.h | grep define| grep get_type | sed -e 's/#define [0-9,A-Z,_ ]*//' -e 's/[),( ]*//g'`

for type_fun in $type_funs;do
    echo "extern GType $type_fun (void);"
done

echo "

void
gegl_register_type (GType type)
{
  g_type_class_ref (type);
}"
      
echo ""
echo "void"
echo "$1_init_types (void)"
echo "{"
for type_fun in $type_funs;do
    echo "  gegl_register_type ($type_fun ());"
done
echo "}"
